// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package iblog

type NewPost struct {
	Title     string   `json:"title"`
	Content   string   `json:"content"`
	TagsTitle []string `json:"tagsTitle"`
}

type UpdatePost struct {
	Title     string   `json:"title"`
	Content   string   `json:"content"`
	TagsTitle []string `json:"tagsTitle"`
}
